# Generated by Django 4.1.5 on 2023-02-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_alter_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(max_length=150, verbose_name='Portfolio Name'),
        ),
    ]
