# Generated by Django 4.1.5 on 2023-02-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_alter_portfolio_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='images/'),
        ),
    ]
