# Generated by Django 4.1.5 on 2023-02-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_alter_portfolio_portfolio_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='images/')),
                ('testimonial_quotation', models.CharField(max_length=50)),
                ('testimonial_desc', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile_name', models.CharField(max_length=20)),
                ('profile_location', models.CharField(max_length=30)),
            ],
        ),
    ]
