# Generated by Django 4.1.5 on 2023-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0011_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_desc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_quotation',
            field=models.CharField(max_length=70),
        ),
    ]
