# Generated by Django 4.1.5 on 2023-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0012_alter_testimonial_testimonial_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
