# Generated by Django 4.1.5 on 2023-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0013_testimonial_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_category', models.CharField(max_length=20)),
                ('article_date', models.CharField(max_length=30)),
                ('article_header', models.CharField(max_length=150)),
                ('aricle_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='images/')),
            ],
        ),
    ]
