# Generated by Django 4.1.5 on 2023-02-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0014_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='aricle_image',
            new_name='article_image',
        ),
    ]
