# Generated by Django 4.1.5 on 2023-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0015_rename_aricle_image_articles_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(max_length=150, upload_to='images/')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_occupation', models.CharField(max_length=70)),
                ('quote', models.TextField(max_length=300)),
            ],
        ),
    ]
