from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name="index"),
    path('about', views.about, name="about"),
    path('blog',views.blog, name="blog"),
    path('contact',views.contact,name="contact"),
    path('portfolio',views.portfolio, name="portfolio"),
    path('add_services', views.add_services, name="add-services"),
    path("list_services", views.list_services, name="list-services"),
    path("show_service/<service_id>", views.show_service, name="show-service"),
    path("update_service/<service_id>", views.update_service, name="update-service"),
    path("delete_service/<service_id>", views.delete_service, name="delete-service"),
    path("add_portfolio", views.add_portfolio, name="add-portfolio"),
    path("list_portfolio", views.list_portfolio, name="list-portfolios"),
    path("update_portfolio/<portfolio_id>", views.update_portfolio, name="update-portfolio"),
    path("delete_portfolio/<portfolio_id>", views.delete_portfolio, name="delete-portfolio"),
    path("add_testimonial", views.add_testimonial, name="add-testimonial"),
    path("list_testimonial", views.list_testimonial, name="list-testimonial"),
    path("update_testimonial/<testimonial_id>",views.update_testimonial, name="update-testimonial"),
    path("delete_testimonial/<testimonial_id>",views.delete_testimonial, name="delete-testimonial"),
    path("admin_approval", views.admin_approval, name="admin-approval"),
    path('add_article', views.add_article, name="add-article"),
    path('list_articles', views.list_articles, name="list-articles"),
    path("update_article/<article_id>",views.update_article, name="update-article"),
    path("delete_article/<article_id>", views.delete_article, name="delete-article"),
    path('add_team',views.add_team,name="add-team"),
    path('list_team',views.list_team,name="list-team"),
    path("update_team/<team_id>",views.update_team, name="update-team"),
    path("delete_team/<team_id>",views.delete_team, name="delete-team"),
    path("add_office",views.add_office, name="add-office"),
    path("list_offices", views.list_offices,name="list-offices"),
    path("update_office/<office_id>",views.update_office, name="update-office"),
    path("delete_office/<office_id>",views.delete_office, name="delete-office"),
    path("show_services",views.show_services, name="show-services"),
    path('trends_articles',views.trends_articles, name="trends"),
    path('resources_articles',views.resources_articles, name="resources"),
    path('design_articles',views.design_articles, name="designs"),
]
